version: "3"
services:
  redis:
    image: redis@sha256:fed4c3c120450b140aaff9b125306cc58aba99876399b081a6ba054c0328a189
    command: redis-server --requirepass password
    expose:
      - 6379
  agentfrontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: npm start
    depends_on:
      - redis
    volumes:
      - ./:/home/node/agent-ui
      - /home/node/agent-ui/node_modules/
    ports:
      - "3002:3002"
    environment:
      CONTEXT_PATH: ${CONTEXT_PATH}
      PORT: ${PORT}
