version: "3"
services:
  redis:
    image: redis@sha256:cd015a1d1e6a485ee71a656a17a6a35d32819175b67fa6ee3c47b6fb6141cbe1
    command: redis-server --requirepass password
    expose:
      - 6379
  agentfrontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: npm start
    depends_on:
      - redis
    volumes:
      - ./:/home/node/agent-ui
      - /home/node/agent-ui/node_modules/
    ports:
      - "3002:3002"
    environment:
      CONTEXT_PATH: ${CONTEXT_PATH}
      PORT: ${PORT}
