version: "3"
services:
  redis:
    image: redis@sha256:552d17f7929fc0b70a17c0cdbd61371a58a5953bf0e2cb7849bca7b42346bce1
    command: redis-server --requirepass password
    expose:
      - 6379
  agentfrontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: npm start
    depends_on:
      - redis
    volumes:
      - ./:/home/node/agent-ui
      - /home/node/agent-ui/node_modules/
    ports:
      - "3002:3002"
    environment:
      CONTEXT_PATH: ${CONTEXT_PATH}
      PORT: ${PORT}
