version: "3"
services:
  redis:
    image: redis@sha256:e73ef998c22f9a98793d9951bb2915cd945d8fa6f9ec1b324e85d19617efc2fd
    expose:
      - 6379
  agent_frontend:
    build: ./
    command: npm start
    depends_on:
      - redis
    volumes:
      - nodemodules:/usr/src/app/node_modules
      - ./:/usr/src/app
    ports:
      - "3002:3002"
    environment:
      REDIS_HOST: redis
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      CUSTOMERAPIGATEWAY: ${CUSTOMER_API_GATEWAY}
      NODE_EXTRA_CA_CERTS: ${NODE_EXTRA_CA_CERTS}
      WEB_APP: host.docker.internal
volumes:
  nodemodules:
    external: true