version: "3"
services:
  redis:
    image: redis@sha256:ee1d00c5250b5a886b09be2d5f9506add35dfb557f1ef37a7e4b8f0138f32956
    expose:
      - 6379
  agent_frontend:
    build: ./
    command: npm start
    depends_on:
      - redis
    volumes:
      - nodemodules:/usr/src/app/node_modules
      - ./:/usr/src/app
    ports:
      - "3002:3002"
    environment:
      REDIS_HOST: redis
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      CUSTOMERAPIGATEWAY: ${CUSTOMER_API_GATEWAY}
      NODE_EXTRA_CA_CERTS: ${NODE_EXTRA_CA_CERTS}
      WEB_APP: host.docker.internal
volumes:
  nodemodules:
    external: true