version: "3"
services:
  redis:
    image: redis@sha256:000339fb57e0ddf2d48d72f3341e47a8ca3b1beae9bdcb25a96323095b72a79b
    expose:
      - 6379
  agent_frontend:
    build: ./
    command: npm start
    depends_on:
      - redis
    volumes:
      - ./:/usr/src/app
    ports:
      - "3002:3002"
    environment:
      REDIS_HOST: redis
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      CUSTOMERAPIGATEWAY: ${CUSTOMER_API_GATEWAY}
      NODE_EXTRA_CA_CERTS: ${NODE_EXTRA_CA_CERTS}
      WEB_APP: host.docker.internal
