module.exports = {
  multipleAddresses() {
    return { ...this.addressBase() };
  },
  multipleAddressesNoneEmpty() {
    return { ...this.addressBaseNonEmpty() };
  },
  multipleAddressesAllEmpty() {
    return { ...this.addressBaseAllEmpty() };
  },
  singleAddress() {
    const address = { ...this.addressBase().data[0] };
    return { data: [address] };
  },
  addressWithNoDepThoroughAndTownNameFieldPresent() {
    return { ...this.addressWithNoDepThoroughAndTownNameFieldIsPresent() };
  },
  multipleAddressesList() {
    return [{
      text: '2 addresses found',
    }, {
      value: '10091853817',
      text: '1/L 1 WINDSOR PLACE, MAIN STREET, BRIDGE OF WEIR, PA11 3AF',
    }, {
      value: '10091853817',
      text: '1/L 1 WINDSOR PLACE, MAIN STREET, BRIDGE OF WEIR, PA11 3AF',
    }];
  },
  singleAddressesList() {
    return [{
      text: '1 address found',
    }, {
      value: '10091853817',
      text: '1/L 1 WINDSOR PLACE, MAIN STREET, BRIDGE OF WEIR, PA11 3AF',
    }];
  },
  addressBase() {
    return {
      data: [{
        key: 'GBR-123003673',
        uprn: '10091853817',
        org: [],
        subBuilding: '1/L',
        poBoxNumber: null,
        buildingName: 'Name',
        buildingNumber: '1',
        street: ['WINDSOR PLACE', 'MAIN STREET'],
        locality: ['dependentLocality'],
        postTown: 'BRIDGE OF WEIR',
        postcode: 'PA11 3AF',
        countryCode: 'GBR',
        singleLine: '1/L 1 WINDSOR PLACE, MAIN STREET, BRIDGE OF WEIR, PA11 3AF',
        alternateSingleLine: 'FLAT 1/1, 1 WINDSOR PLACE, MAIN STREET, BRIDGE OF WEIR, PA11 3AF',
        lines: ['1/L 1 WINDSOR PLACE', 'MAIN STREET', 'BRIDGE OF WEIR', 'PA11 3AF'],
        homeNationCode: 'SCT',
        addressType: {
          osLevel1Class: 'R',
          osLevel2Class: 'D',
          osLevel3Class: '6',
          osLevel4Class: '',
          osLevel1Description: 'RESIDENTIAL',
          osLevel2Description: 'DWELLING',
          osLevel3Description: 'SELF CONTAINED FLAT (INCLUDES MAISONETTE / APARTMENT)',
          osLevel4Description: '',
        },
        metaData: {
          source: 'ORDNANCE_SURVEY',
        },
        sourceData: {
          uprn: 10091853817,
          udprn: 15860303,
          parentUprn: null,
          organisationName: null,
          laOrganisationName: null,
          poBoxNumber: null,
          subBuildingName: '1/L',
          buildingName: null,
          buildingNumber: '1',
          streetDescription: 'MAIN STREET',
          doubleDependentLocality: null,
          departmentName: null,
          dependentLocality: 'dependentLocality',
          locality: null,
          postTown: 'BRIDGE OF WEIR',
          townName: 'BRIDGE OF WEIR',
          postcodeLocator: 'PA11 3AF',
          paoText: null,
          paoStartNumber: null,
          paoStartSuffix: null,
          paoEndNumber: null,
          paoEndSuffix: null,
          saoText: null,
          saoStartNumber: null,
          saoStartSuffix: null,
          saoEndNumber: null,
          saoEndSuffix: null,
          addressbasePostal: 'D',
          wardCode: 'E05011452',
          voaNdrpDescCode: null,
          voaNdrScatCode: '249',
          country: 'E',
          state: '2',
          administrativeArea: null,
          class: 'CR08',
          dependentThoroughfare: 'WINDSOR PLACE',
          thoroughfare: 'MAIN STREET',
        },
      }, {
        key: 'GBR-123003673',
        uprn: '10091853817',
        org: [],
        subBuilding: '1/L',
        poBoxNumber: null,
        buildingName: 'Name',
        buildingNumber: '1',
        street: ['WINDSOR PLACE', 'MAIN STREET'],
        locality: ['dependentLocality'],
        postTown: 'BRIDGE OF WEIR',
        postcode: 'PA11 3AF',
        countryCode: 'GBR',
        singleLine: '1/L 1 WINDSOR PLACE, MAIN STREET, BRIDGE OF WEIR, PA11 3AF',
        alternateSingleLine: 'FLAT 1/1, 1 WINDSOR PLACE, MAIN STREET, BRIDGE OF WEIR, PA11 3AF',
        lines: ['1/L 1 WINDSOR PLACE', 'MAIN STREET', 'BRIDGE OF WEIR', 'PA11 3AF'],
        homeNationCode: 'SCT',
        addressType: {
          osLevel1Class: 'R',
          osLevel2Class: 'D',
          osLevel3Class: '6',
          osLevel4Class: '',
          osLevel1Description: 'RESIDENTIAL',
          osLevel2Description: 'DWELLING',
          osLevel3Description: 'SELF CONTAINED FLAT (INCLUDES MAISONETTE / APARTMENT)',
          osLevel4Description: '',
        },
        metaData: {
          source: 'ORDNANCE_SURVEY',
        },
        sourceData: {
          uprn: 10091853817,
          udprn: 15860303,
          parentUprn: null,
          organisationName: null,
          laOrganisationName: null,
          poBoxNumber: null,
          subBuildingName: '1/L',
          buildingName: null,
          buildingNumber: '1',
          streetDescription: 'MAIN STREET',
          doubleDependentLocality: null,
          departmentName: null,
          dependentLocality: 'dependentLocality',
          locality: null,
          postTown: 'BRIDGE OF WEIR',
          townName: 'BRIDGE OF WEIR',
          postcodeLocator: 'PA11 3AF',
          paoText: null,
          paoStartNumber: null,
          paoStartSuffix: null,
          paoEndNumber: null,
          paoEndSuffix: null,
          saoText: null,
          saoStartNumber: null,
          saoStartSuffix: null,
          saoEndNumber: null,
          saoEndSuffix: null,
          addressbasePostal: 'D',
          wardCode: 'E05011452',
          voaNdrpDescCode: null,
          voaNdrScatCode: '249',
          country: 'E',
          state: '2',
          administrativeArea: null,
          class: 'CR08',
          dependentThoroughfare: 'WINDSOR PLACE',
          thoroughfare: 'MAIN STREET',
        },
      }],
    };
  },
  addressBaseNonEmpty() {
    return {
      data: [{
        key: 'GBR-123003673',
        uprn: '10091853817',
        org: [],
        subBuilding: 'subBuildingName',
        poBoxNumber: 'poBoxNumber',
        buildingName: 'buildingName',
        buildingNumber: '148',
        street: ['dependentThoroughfareName', 'PICCADILLY'],
        locality: ['dependentLocality'],
        postTown: 'LONDON',
        postcode: 'W1J 7NT',
        countryCode: 'GBR',
        singleLine: '148 PICCADILLY, LONDON, W1J 7NT',
        alternateSingleLine: 'F148 PICCADILLY, LONDON, W1J 7NT',
        lines: ['148 PICCADILLY, LONDON, W1J 7NT'],
        homeNationCode: 'SCT',
        addressType: {
          osLevel1Class: 'R',
          osLevel2Class: 'D',
          osLevel3Class: '6',
          osLevel4Class: '',
          osLevel1Description: 'RESIDENTIAL',
          osLevel2Description: 'DWELLING',
          osLevel3Description: 'SELF CONTAINED FLAT (INCLUDES MAISONETTE / APARTMENT)',
          osLevel4Description: '',
        },
        metaData: {
          source: 'ORDNANCE_SURVEY',
        },
        sourceData: {
          uprn: 10091853817,
          udprn: 15860303,
          parentUprn: null,
          organisationName: null,
          laOrganisationName: null,
          poBoxNumber: null,
          subBuildingName: '1/L',
          buildingName: null,
          buildingNumber: '1',
          streetDescription: 'MAIN STREET',
          doubleDependentLocality: null,
          departmentName: null,
          dependentLocality: 'dependentLocality',
          locality: null,
          postTown: 'BRIDGE OF WEIR',
          townName: 'BRIDGE OF WEIR',
          postcodeLocator: 'PA11 3AF',
          paoText: null,
          paoStartNumber: null,
          paoStartSuffix: null,
          paoEndNumber: null,
          paoEndSuffix: null,
          saoText: null,
          saoStartNumber: null,
          saoStartSuffix: null,
          saoEndNumber: null,
          saoEndSuffix: null,
          addressbasePostal: 'D',
          wardCode: 'E05011452',
          voaNdrpDescCode: null,
          voaNdrScatCode: '249',
          country: 'E',
          state: '2',
          administrativeArea: null,
          class: 'CR08',
          dependentThoroughfare: 'dependentThoroughfareName',
          thoroughfare: 'PICCADILLY',
        },
      }, {
        key: 'GBR-123003673',
        uprn: '10091853817',
        org: [],
        subBuilding: 'subBuildingName',
        poBoxNumber: 'poBoxNumber',
        buildingName: 'buildingName',
        buildingNumber: '148',
        street: ['dependentThoroughfareName', 'PICCADILLY'],
        locality: ['dependentLocality'],
        postTown: 'LONDON',
        postcode: 'W1J 7NT',
        countryCode: 'GBR',
        singleLine: '148 PICCADILLY, LONDON, W1J 7NT',
        alternateSingleLine: 'F148 PICCADILLY, LONDON, W1J 7NT',
        lines: ['148 PICCADILLY, LONDON, W1J 7NT'],
        homeNationCode: 'SCT',
        addressType: {
          osLevel1Class: 'R',
          osLevel2Class: 'D',
          osLevel3Class: '6',
          osLevel4Class: '',
          osLevel1Description: 'RESIDENTIAL',
          osLevel2Description: 'DWELLING',
          osLevel3Description: 'SELF CONTAINED FLAT (INCLUDES MAISONETTE / APARTMENT)',
          osLevel4Description: '',
        },
        metaData: {
          source: 'ORDNANCE_SURVEY',
        },
        sourceData: {
          uprn: 10091853817,
          udprn: 15860303,
          parentUprn: null,
          organisationName: null,
          laOrganisationName: null,
          poBoxNumber: null,
          subBuildingName: '1/L',
          buildingName: null,
          buildingNumber: '1',
          streetDescription: 'MAIN STREET',
          doubleDependentLocality: null,
          departmentName: null,
          dependentLocality: 'dependentLocality',
          locality: null,
          postTown: 'BRIDGE OF WEIR',
          townName: 'BRIDGE OF WEIR',
          postcodeLocator: 'PA11 3AF',
          paoText: null,
          paoStartNumber: null,
          paoStartSuffix: null,
          paoEndNumber: null,
          paoEndSuffix: null,
          saoText: null,
          saoStartNumber: null,
          saoStartSuffix: null,
          saoEndNumber: null,
          saoEndSuffix: null,
          addressbasePostal: 'D',
          wardCode: 'E05011452',
          voaNdrpDescCode: null,
          voaNdrScatCode: '249',
          country: 'E',
          state: '2',
          administrativeArea: null,
          class: 'CR08',
          dependentThoroughfare: 'dependentThoroughfareName',
          thoroughfare: 'PICCADILLY',
        },
      }],
    };
  },
  addressWithNoDepThoroughAndTownNameFieldIsPresent() {
    return {
      data: [{
        key: 'GBR-123003673',
        uprn: '10091853817',
        org: [],
        subBuilding: 'subBuildingName',
        poBoxNumber: 'poBoxNumber',
        buildingName: 'buildingName',
        buildingNumber: '148',
        street: ['PICCADILLY'],
        locality: ['dependentLocality'],
        postcode: 'W1J 7NT',
        countryCode: 'GBR',
        singleLine: '148 PICCADILLY, LONDON, W1J 7NT',
        alternateSingleLine: 'F148 PICCADILLY, LONDON, W1J 7NT',
        lines: ['148 PICCADILLY, LONDON, W1J 7NT'],
        homeNationCode: 'SCT',
        addressType: {
          osLevel1Class: 'R',
          osLevel2Class: 'D',
          osLevel3Class: '6',
          osLevel4Class: '',
          osLevel1Description: 'RESIDENTIAL',
          osLevel2Description: 'DWELLING',
          osLevel3Description: 'SELF CONTAINED FLAT (INCLUDES MAISONETTE / APARTMENT)',
          osLevel4Description: '',
        },
        metaData: {
          source: 'ORDNANCE_SURVEY',
        },
        sourceData: {
          uprn: 10091853817,
          udprn: 15860303,
          parentUprn: null,
          organisationName: null,
          laOrganisationName: null,
          poBoxNumber: null,
          subBuildingName: '1/L',
          buildingName: null,
          buildingNumber: '1',
          streetDescription: 'MAIN STREET',
          doubleDependentLocality: null,
          departmentName: null,
          dependentLocality: 'dependentLocality',
          locality: null,
          townName: 'BRIDGE OF WEIR',
          postcodeLocator: 'PA11 3AF',
          paoText: null,
          paoStartNumber: null,
          paoStartSuffix: null,
          paoEndNumber: null,
          paoEndSuffix: null,
          saoText: null,
          saoStartNumber: null,
          saoStartSuffix: null,
          saoEndNumber: null,
          saoEndSuffix: null,
          addressbasePostal: 'D',
          wardCode: 'E05011452',
          voaNdrpDescCode: null,
          voaNdrScatCode: '249',
          country: 'E',
          state: '2',
          administrativeArea: null,
          class: 'CR08',
          dependentThoroughfare: null,
          thoroughfare: null,
        },
      }],
    };
  },
  addressBaseAllEmpty() {
    return {
      data: [{
        key: null,
        uprn: '10091853817',
        org: [],
        subBuilding: null,
        poBoxNumber: null,
        buildingName: null,
        buildingNumber: null,
        street: [],
        locality: [],
        postTown: null,
        postcode: null,
        countryCode: null,
        singleLine: null,
        alternateSingleLine: null,
        lines: [],
        homeNationCode: null,
        addressType: {
          osLevel1Class: null,
          osLevel2Class: null,
          osLevel3Class: null,
          osLevel4Class: null,
          osLevel1Description: null,
          osLevel2Description: null,
          osLevel3Description: null,
          osLevel4Description: null,
        },
        metaData: {
          source: 'ORDNANCE_SURVEY',
        },
        sourceData: {
          uprn: 4510006755,
          udprn: null,
          parentUprn: null,
          organisationName: null,
          laOrganisationName: null,
          poBoxNumber: null,
          subBuildingName: null,
          buildingName: null,
          buildingNumber: null,
          streetDescription: null,
          doubleDependentLocality: null,
          departmentName: null,
          dependentLocality: null,
          locality: null,
          postTown: null,
          townName: null,
          postcodeLocator: null,
          paoText: null,
          paoStartNumber: null,
          paoStartSuffix: null,
          paoEndNumber: null,
          paoEndSuffix: null,
          saoText: null,
          saoStartNumber: null,
          saoStartSuffix: null,
          saoEndNumber: null,
          saoEndSuffix: null,
          addressbasePostal: null,
          wardCode: null,
          voaNdrpDescCode: null,
          voaNdrScatCode: null,
          country: null,
          state: null,
          administrativeArea: null,
          class: null,
          dependentThoroughfare: null,
          thoroughfare: null,
        },
      }, {
        key: null,
        uprn: '10091853817',
        org: [],
        subBuilding: null,
        poBoxNumber: null,
        buildingName: null,
        buildingNumber: null,
        street: [],
        locality: [],
        postTown: null,
        postcode: null,
        countryCode: null,
        singleLine: null,
        alternateSingleLine: null,
        lines: [],
        homeNationCode: null,
        addressType: {
          osLevel1Class: null,
          osLevel2Class: null,
          osLevel3Class: null,
          osLevel4Class: null,
          osLevel1Description: null,
          osLevel2Description: null,
          osLevel3Description: null,
          osLevel4Description: null,
        },
        metaData: {
          source: 'ORDNANCE_SURVEY',
        },
        sourceData: {
          uprn: 4510006755,
          udprn: null,
          parentUprn: null,
          organisationName: null,
          laOrganisationName: null,
          poBoxNumber: null,
          subBuildingName: null,
          buildingName: null,
          buildingNumber: null,
          streetDescription: null,
          doubleDependentLocality: null,
          departmentName: null,
          dependentLocality: null,
          locality: null,
          postTown: null,
          townName: null,
          postcodeLocator: null,
          paoText: null,
          paoStartNumber: null,
          paoStartSuffix: null,
          paoEndNumber: null,
          paoEndSuffix: null,
          saoText: null,
          saoStartNumber: null,
          saoStartSuffix: null,
          saoEndNumber: null,
          saoEndSuffix: null,
          addressbasePostal: null,
          wardCode: null,
          voaNdrpDescCode: null,
          voaNdrScatCode: null,
          country: null,
          state: null,
          administrativeArea: null,
          class: null,
          dependentThoroughfare: null,
          thoroughfare: null,
        },
      }],
    };
  },
};
